// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Nmo1ZDVLoouQ8grPsXhQE_7Ue1ecqcQ',
    appId: '1:840323369559:web:8e2b01bf6af45b6d663112',
    messagingSenderId: '840323369559',
    projectId: 'mogha-266d4',
    authDomain: 'mogha-266d4.firebaseapp.com',
    storageBucket: 'mogha-266d4.appspot.com',
    measurementId: 'G-39PQ6KF7E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVe01jcmzcjj_ivuuLegzzvjOi2eb6tM',
    appId: '1:840323369559:android:1989d5f504943ae3663112',
    messagingSenderId: '840323369559',
    projectId: 'mogha-266d4',
    storageBucket: 'mogha-266d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvu_SNACvTs3ORMMbQ_tJqVkeGIkoNSG4',
    appId: '1:840323369559:ios:332d1f81533f8d8a663112',
    messagingSenderId: '840323369559',
    projectId: 'mogha-266d4',
    storageBucket: 'mogha-266d4.appspot.com',
    iosBundleId: 'com.example.moga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvu_SNACvTs3ORMMbQ_tJqVkeGIkoNSG4',
    appId: '1:840323369559:ios:f2aff49a8ce8c8fd663112',
    messagingSenderId: '840323369559',
    projectId: 'mogha-266d4',
    storageBucket: 'mogha-266d4.appspot.com',
    iosBundleId: 'com.example.moga.RunnerTests',
  );
}
